<?php

namespace QuestBundle\Repository;

/**
 * UserQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
